### ISSUE TITLE
Do the FreeCAD Path devs know about this?

### ISSUE THREAD

**Issue by luzpaz** [fra589/grbl_post#1]
If not, please be so kind and let them and the community know.
https://forum.freecadweb.org/viewforum.php?f=15

**Comment by fra589** [comment]
Hi @luzpaz,  
I opened a topic on the forum during the first version of this post processor, I just updated it:  
https://forum.freecadweb.org/viewtopic.php?f=15&t=25604&p=273970#top  
@++;
Gauthier.
